FROM ruby:2.5.3
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nodejs yarn postgresql-client
COPY ./* /srv/
WORKDIR /srv
RUN bundle install
